### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by Gvinkc** [aiqm/torchani#195]
Hi, I am trying to run in macbook pro. Could you please help on the following error?
Traceback (most recent call last):
  File "energy_force.py", line 13, in <module>
    import torch
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: dlopen(/anaconda3/envs/py36/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so, 9): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libshm.dylib
  Reason: image not found

**Comment by zasdfgbnm** [comment]
Hi @Gvinkc ,

This problem seems to be a problem of PyTorch. Did you correctly installed PyTorch?  I suggest you to write a one line script to check if PyTorch is installed correctly:

```python
import torch
```
Run the above script, and you should see the same problem.

I suggest you to reinstall PyTorch, and if the problem still persist, then go to https://discuss.pytorch.org/ for help.

**Comment by Gvinkc** [comment]
Thank you for the response. Yes it was related with the PyTorch. I fixed the issue by running:
'brew install libomap'

**Comment by zasdfgbnm** [comment]
@Gvinkc It's good to hear that you are able to solve the problem. Closing this issue now.
