### ISSUE TITLE
Unable to export neural network

### ISSUE THREAD

**Issue by tengjieksee** [aiqm/torchani#551]
Hi everyone, I just wanna ask how do I export the neural network into the format like the ani-1x_8x model as shown in the fig below?

<img width="916" alt="anipic" src="https://user-images.githubusercontent.com/47586439/99742558-dc058400-2b27-11eb-9fba-435dbfe6601b.png">

(https://github.com/aiqm/ani-model-zoo/tree/master/resources/ani-1x_8x)

So far, I managed to run the nnp_training.ipnyb (https://aiqm.github.io/torchani/examples/nnp_training.html) example and I managed to get the checkpoint file of the neural network but I couldn't find any way to export the network into that format.

Any help would be appreciated.

**Comment by yueyericardo** [comment]
Hi, the one you are saying is or internal neurochem format, you don’t need to save as this format.
Refer to this page https://aiqm.github.io/torchani/examples/nnp_training.html, about how to use torch.save() save your model.

**Comment by IgnacioJPickering** [comment]
@tengjieksee neurochem format is essentially deprecated and we only use it for legacy reasons. There may be networks trained in the future using neurochem format that will be provided with torchani, but the idea is not for users to save in this format since it serves no real purpose. I recommend you use either torch.save() or you save the parameter dict of your models https://pytorch.org/tutorials/beginner/saving_loading_models.html 
That may be useful

**Comment by tengjieksee** [comment]
Are there any ways to create the neurochem format even though it is depreciated?

**Comment by zasdfgbnm** [comment]
Hi @tengjieksee I don't think we have time to implement a writer for NeuroChem format. If you are really interested, you can reverse engineer the loader code and write a converter based on that.
